apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-argo
  namespace: machina-sbx
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: argocd-declartive-app-project
  project: default
  source:
    repoURL: https://github.com/anilsoni007/gitops-argocd-app.git  
    targetRevision: main  
    path: ./declarative

  destination:
    server: https://kubernetes.default.svc  
    namespace: machina-sbx  
  syncPolicy:
    automated:
      prune: true  
      selfHeal: true  
    syncOptions:
      - CreateNamespace=true 
