apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-argo
  namespace: machina-sbx
spec:
  project: default

  source:
    repoURL: https://github.com/anilsoni007/gitops-argocd-app.git  
    targetRevision: HEAD  
    path: ./declarative

  destination:
    server: https://kubernetes.default.svc  
    namespace: machina-sbx  
  syncPolicy:
    automated:
      prune: true  
      selfHeal: true  
    syncOptions:
      - CreateNamespace=true 
