apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-argo-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/anilsoni007/gitops-argocd-app.git
    targetRevision: main
    path: ./declarative
   
  destination:
    server: https://kubernetes.default.svc
    namespace: machina-sbx

  syncPolicy:
    syncOptions:
      - CreateNamespace=true  
    automated:
      prune: true
      selfHeal: true