apiVersion: v1
kind: Service
metadata:
  labels:
    app: secret-app
  name: secret-app
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30962
  selector:
    app: secret-app
  type: NodePort